export const states = [
    { name: 'Acre', abbr: 'AC' },
    { name: 'Alagoas', abbr: 'AL' },
    { name: 'Amapá', abbr: 'AP' },
    { name: 'Amazonas', abbr: 'AM' },
    { name: 'Bahia', abbr: 'BA' },
    { name: 'Ceará', abbr: 'CE' },
    { name: 'Distrito Federal', abbr: 'DF' },
    { name: 'Espírito Santo', abbr: 'ES' },
    { name: 'Goiás', abbr: 'GO' },
    { name: 'Maranhão', abbr: 'MA' },
    { name: 'Mato Grosso', abbr: 'MT' },
    { name: 'Mato Grosso do Sul', abbr: 'MS' },
    { name: 'Minas Gerais', abbr: 'MG' },
    { name: 'Pará', abbr: 'PA' },
    { name: 'Paraíba', abbr: 'PB' },
    { name: 'Paraná', abbr: 'PR' },
    { name: 'Pernambuco', abbr: 'PE' },
    { name: 'Piauí', abbr: 'PI' },
    { name: 'Rio de Janeiro', abbr: 'RJ' },
    { name: 'Rio Grande do Norte', abbr: 'RN' },
    { name: 'Rio Grande do Sul', abbr: 'RS' },
    { name: 'Rondônia', abbr: 'RO' },
    { name: 'Roraima', abbr: 'RR' },
    { name: 'Santa Catarina', abbr: 'SC' },
    { name: 'São Paulo', abbr: 'SP' },
    { name: 'Sergipe', abbr: 'SE' },
    { name: 'Tocantins', abbr: 'TO' }
];

export const cities: Record<string, string[]> = {
    AC: ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira', 'Tarauacá'],
    AL: ['Maceió', 'Arapiraca', 'Palmeira dos Índios', 'Rio Largo'],
    AP: ['Macapá', 'Santana', 'Laranjal do Jari', 'Oiapoque'],
    AM: ['Manaus', 'Parintins', 'Itacoatiara', 'Manacapuru'],
    BA: ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari', 'Juazeiro', 'Ilhéus', 'Lauro de Freitas'],
    CE: ['Fortaleza', 'Caucaia', 'Juazeiro do Norte', 'Maracanaú', 'Sobral'],
    DF: ['Brasília'],
    ES: ['Vitória', 'Vila Velha', 'Serra', 'Cariacica', 'Cachoeiro de Itapemirim'],
    GO: ['Goiânia', 'Aparecida de Goiânia', 'Anápolis', 'Rio Verde', 'Luziânia'],
    MA: ['São Luís', 'Imperatriz', 'São José de Ribamar', 'Timon', 'Caxias'],
    MT: ['Cuiabá', 'Várzea Grande', 'Rondonópolis', 'Sinop', 'Tangará da Serra'],
    MS: ['Campo Grande', 'Dourados', 'Três Lagoas', 'Corumbá'],
    MG: ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora', 'Betim', 'Montes Claros', 'Uberaba'],
    PA: ['Belém', 'Ananindeua', 'Santarém', 'Marabá', 'Parauapebas'],
    PB: ['João Pessoa', 'Campina Grande', 'Santa Rita', 'Patos', 'Bayeux'],
    PR: ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa', 'Cascavel', 'Foz do Iguaçu'],
    PE: ['Recife', 'Jaboatão dos Guararapes', 'Olinda', 'Caruaru', 'Paulista', 'Petrolina'],
    PI: ['Teresina', 'Parnaíba', 'Picos', 'Piripiri'],
    RJ: ['Rio de Janeiro', 'São Gonçalo', 'Duque de Caxias', 'Nova Iguaçu', 'Niterói', 'Belford Roxo', 'Campos dos Goytacazes', 'São João de Meriti'],
    RN: ['Natal', 'Mossoró', 'Parnamirim', 'São Gonçalo do Amarante'],
    RS: ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Canoas', 'Santa Maria', 'Gravataí'],
    RO: ['Porto Velho', 'Ji-Paraná', 'Ariquemes', 'Vilhena'],
    RR: ['Boa Vista'],
    SC: ['Florianópolis', 'Joinville', 'Blumenau', 'São José', 'Chapecó', 'Criciúma'],
    SP: ['São Paulo', 'Guarulhos', 'Campinas', 'São Bernardo do Campo', 'Santo André', 'Osasco', 'Ribeirão Preto', 'Sorocaba', 'Santos', 'Jundiaí'],
    SE: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto', 'Itabaiana'],
    TO: ['Palmas', 'Araguaína', 'Gurupi']
};