
export const states = [
    { name: 'Acre', abbr: 'AC' },
    { name: 'Alagoas', abbr: 'AL' },
    { name: 'Amapá', abbr: 'AP' },
    { name: 'Amazonas', abbr: 'AM' },
    { name: 'Bahia', abbr: 'BA' },
    { name: 'Ceará', abbr: 'CE' },
    { name: 'Distrito Federal', abbr: 'DF' },
    { name: 'Espírito Santo', abbr: 'ES' },
    { name: 'Goiás', abbr: 'GO' },
    { name: 'Maranhão', abbr: 'MA' },
    { name: 'Mato Grosso', abbr: 'MT' },
    { name: 'Mato Grosso do Sul', abbr: 'MS' },
    { name: 'Minas Gerais', abbr: 'MG' },
    { name: 'Pará', abbr: 'PA' },
    { name: 'Paraíba', abbr: 'PB' },
    { name: 'Paraná', abbr: 'PR' },
    { name: 'Pernambuco', abbr: 'PE' },
    { name: 'Piauí', abbr: 'PI' },
    { name: 'Rio de Janeiro', abbr: 'RJ' },
    { name: 'Rio Grande do Norte', abbr: 'RN' },
    { name: 'Rio Grande do Sul', abbr: 'RS' },
    { name: 'Rondônia', abbr: 'RO' },
    { name: 'Roraima', abbr: 'RR' },
    { name: 'Santa Catarina', abbr: 'SC' },
    { name: 'São Paulo', abbr: 'SP' },
    { name: 'Sergipe', abbr: 'SE' },
    { name: 'Tocantins', abbr: 'TO' }
];

export const cities: Record<string, string[]> = {
    AC: ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira', 'Tarauacá', 'Feijó'],
    AL: ['Maceió', 'Arapiraca', 'Palmeira dos Índios', 'Rio Largo', 'Penedo'],
    AP: ['Macapá', 'Santana', 'Laranjal do Jari', 'Oiapoque', 'Mazagão'],
    AM: ['Manaus', 'Parintins', 'Itacoatiara', 'Manacapuru', 'Coari'],
    BA: ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari', 'Juazeiro', 'Ilhéus', 'Lauro de Freitas', 'Itabuna', 'Barreiras'],
    CE: ['Fortaleza', 'Caucaia', 'Juazeiro do Norte', 'Maracanaú', 'Sobral', 'Iguatu', 'Crato'],
    DF: ['Brasília'],
    ES: ['Vitória', 'Vila Velha', 'Serra', 'Cariacica', 'Cachoeiro de Itapemirim', 'Linhares', 'Colatina'],
    GO: ['Goiânia', 'Aparecida de Goiânia', 'Anápolis', 'Rio Verde', 'Luziânia', 'Águas Lindas de Goiás', 'Valparaíso de Goiás'],
    MA: ['São Luís', 'Imperatriz', 'São José de Ribamar', 'Timon', 'Caxias', 'Codó', 'Paço do Lumiar'],
    MT: ['Cuiabá', 'Várzea Grande', 'Rondonópolis', 'Sinop', 'Tangará da Serra', 'Cáceres'],
    MS: ['Campo Grande', 'Dourados', 'Três Lagoas', 'Corumbá', 'Ponta Porã'],
    MG: ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora', 'Betim', 'Montes Claros', 'Uberaba', 'Ribeirão das Neves', 'Governador Valadares', 'Divinópolis'],
    PA: ['Belém', 'Ananindeua', 'Santarém', 'Marabá', 'Parauapebas', 'Castanhal', 'Abaetetuba'],
    PB: ['João Pessoa', 'Campina Grande', 'Santa Rita', 'Patos', 'Bayeux', 'Sousa'],
    PR: ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa', 'Cascavel', 'Foz do Iguaçu', 'São José dos Pinhais', 'Colombo'],
    PE: ['Recife', 'Jaboatão dos Guararapes', 'Olinda', 'Caruaru', 'Paulista', 'Petrolina', 'Cabo de Santo Agostinho'],
    PI: ['Teresina', 'Parnaíba', 'Picos', 'Piripiri', 'Floriano'],
    RJ: ['Rio de Janeiro', 'São Gonçalo', 'Duque de Caxias', 'Nova Iguaçu', 'Niterói', 'Belford Roxo', 'Campos dos Goytacazes', 'São João de Meriti', 'Petrópolis', 'Volta Redonda', 'Macaé'],
    RN: ['Natal', 'Mossoró', 'Parnamirim', 'São Gonçalo do Amarante', 'Macaíba'],
    RS: ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Canoas', 'Santa Maria', 'Gravataí', 'Viamão', 'Novo Hamburgo', 'São Leopoldo'],
    RO: ['Porto Velho', 'Ji-Paraná', 'Ariquemes', 'Vilhena', 'Cacoal'],
    RR: ['Boa Vista', 'Rorainópolis'],
    SC: [
      'Abdon Batista', 'Abelardo Luz', 'Agrolândia', 'Agronômica', 'Água Doce',
      'Águas de Chapecó', 'Águas Frias', 'Águas Mornas', 'Agudo', 'Ajuricaba',
      'Alecrim', 'Alegrete', 'Alegria', 'Almirante Tamandaré do Sul', 'Alpestre',
      'Alto Alegre', 'Alto Bela Vista', 'Alto Feliz', 'Alvorada', 'Amaral Ferrador',
      'Ametista do Sul', 'André da Rocha', 'Angelina', 'Anita Garibaldi', 'Anitápolis',
      'Anta Gorda', 'Antônio Carlos', 'Antônio Prado', 'Apiúna', 'Arabutã',
      'Araquari', 'Araranguá', 'Armazém', 'Arroio do Meio', 'Arroio do Sal',
      'Arroio do Tigre', 'Arroio dos Ratos', 'Arroio Trinta', 'Arvoredo', 'Arroio Grande',
      'Ascurra', 'Atalanta', 'Augusto Pestana', 'Áurea', 'Aurora',
      'Balneário Arroio do Silva', 'Balneário Barra do Sul', 'Balneário Camboriú',
      'Balneário Gaivota', 'Balneário Piçarras', 'Bandeirante', 'Barra Bonita',
      'Barra do Guarita', 'Barra do Ouro', 'Barra do Quaraí', 'Barra do Ribeiro',
      'Barra do Rio Azul', 'Barra Funda', 'Barra Velha', 'Barracão', 'Barros Cassal',
      'Benjamin Constant do Sul', 'Bento Gonçalves', 'Biguaçu', 'Blumenau', 'Boa Vista das Missões',
      'Boa Vista do Buricá', 'Boa Vista do Cadeado', 'Boa Vista do Incra', 'Boa Vista do Sul', 'Bocaina do Sul',
      'Bom Jesus', 'Bom Jesus do Oeste', 'Bom Jesus do Sul', 'Bom Jardim da Serra', 'Bom Progresso',
      'Bom Retiro', 'Bom Retiro do Sul', 'Bombinhas', 'Botuverá', 'Braga',
      'Braço do Norte', 'Braço do Trombudo', 'Brochier', 'Brunópolis', 'Brusque',
      'Caçador', 'Caçapava do Sul', 'Cacequi', 'Cachoeira do Sul', 'Cachoeirinha',
      'Cacique Doble', 'Caibaté', 'Caiçara', 'Caibi', 'Calmon',
      'Camboriú', 'Campestre da Serra', 'Campina da Lagoa', 'Campina das Missões', 'Campinas do Sul',
      'Campo Belo do Sul', 'Campo Bom', 'Campo Erê', 'Campo Magro', 'Campo Mourão',
      'Campo Novo', 'Campos Borges', 'Campos Novos', 'Canasvieiras', 'Candelária',
      'Cândido Godói', 'Canela', 'Canguçu', 'Canoinhas', 'Capão Alto',
      'Capão Bonito do Sul', 'Capão da Canoa', 'Capão do Cipó', 'Capão do Leão',
      'Capinzal', 'Capitão', 'Capivari de Baixo', 'Capivari do Sul', 'Caraá',
      'Carazinho', 'Carlos Barbosa', 'Carlos Gomes', 'Caseiros', 'Catuípe',
      'Caxias do Sul', 'Celso Ramos', 'Centenário', 'Cerrito', 'Cerro Branco',
      'Cerro Grande', 'Cerro Grande do Sul', 'Cerro Largo', 'Cerro Negro', 'Chapada',
      'Chapecó', 'Charqueadas', 'Charrua', 'Chiapetta', 'Chopinzinho',
      'Chuí', 'Chuvisca', 'Cidreira', 'Ciríaco', 'Clevelândia',
      'Colinas', 'Colorado', 'Concórdia', 'Condor', 'Constantina',
      'Coqueiro Baixo', 'Coqueiros do Sul', 'Coronel Barros', 'Coronel Bicaco',
      'Coronel Freitas', 'Coronel Martins', 'Coronel Pilar', 'Coronel Vivida', 'Corupá',
      'Cotiporã', 'Crissiumal', 'Cristal', 'Cristal do Sul', 'Criciúma',
      'Cruz Alta', 'Cruzaltense', 'Cruzeiro do Sul', 'Cunha Porã', 'Cunhataí',
      'David Canabarro', 'Derrubadas', 'Dezesseis de Novembro', 'Descanso', 'Dilermando de Aguiar',
      'Dois Irmãos', 'Dois Irmãos das Missões', 'Dois Lajeados', 'Dom Feliciano',
      'Dom Pedrito', 'Dom Pedro de Alcântara', 'Dona Francisca', 'Dona Emma',
      'Doutor Maurício Cardoso', 'Doutor Pedrinho', 'Doutor Ricardo', 'Eldorado do Sul',
      'Encantado', 'Encruzilhada do Sul', 'Engenho Velho', 'Entre-Ijuís', 'Entre Rios do Sul',
      'Erebango', 'Erechim', 'Ernestina', 'Erval Grande', 'Erval Seco', 'Erval Velho',
      'Esmeralda', 'Esperança do Sul', 'Espumoso', 'Estação', 'Estância Velha',
      'Esteio', 'Estrela', 'Estrela Velha', 'Faxinal do Soturno', 'Faxinalzinho',
      'Fazenda Vilanova', 'Fagundes Varela', 'Farroupilha', 'Feliz', 'Flor do Sertão',
      'Florianópolis', 'Forquilhinha', 'Formigueiro', 'Formosa do Sul', 'Forquetinha',
      'Fortaleza dos Valos', 'Fraiburgo', 'Frederico Westphalen', 'Galvão', 'Garibaldi',
      'Garopaba', 'Garruchos', 'Gaurama', 'General Câmara', 'Gentil',
      'Getúlio Vargas', 'Giruá', 'Glorinha', 'Gramado', 'Gramado dos Loureiros',
      'Gramado Xavier', 'Gravataí', 'Grão-Pará', 'Guabiju', 'Guaíba',
      'Guaporé', 'Guaraciaba', 'Guaramirim', 'Guaraniaçu', 'Guarani das Missões',
      'Guarujá do Sul', 'Guatambú', 'Herval', 'Herval d\'Oeste', 'Herveiras',
      'Horizontina', 'Hulha Negra', 'Humaitá', 'Ibarama', 'Ibiaçá',
      'Ibiraiaras', 'Ibirapuitã', 'Ibirubá', 'Içara', 'Ilhota',
      'Imbé', 'Imbuia', 'Imigrante', 'Indaial', 'Independência',
      'Inhacorá', 'Iomerê', 'Ipê', 'Ipiranga do Sul', 'Ipira',
      'Ipuaçu', 'Ipumirim', 'Iraí', 'Irani', 'Irati',
      'Itaara', 'Itá', 'Itacurubi', 'Itaiópolis', 'Itajaí',
      'Itapema', 'Itapiranga', 'Itapuca', 'Itati', 'Itatiba do Sul',
      'Ivorá', 'Ivoti', 'Jaboticaba', 'Jacuizinho', 'Jacutinga',
      'Jaguarão', 'Jaguari', 'Jaguaruna', 'Jaquirana', 'Jari',
      'Jóia', 'Joinville', 'José Boiteux', 'Júlio de Castilhos', 'Lacerdópolis',
      'Lagoa Bonita do Sul', 'Lagoa dos Três Cantos', 'Lagoa Vermelha', 'Lagoão',
      'Lages', 'Laguna', 'Lajeado', 'Lajeado do Bugre', 'Lajeado Grande',
      'Laurentino', 'Lauro Müller', 'Lavras do Sul', 'Lebon Régis', 'Leoberto Leal',
      'Liberato Salzano', 'Lindolfo Collor', 'Linha Nova', 'Luzerna', 'Machadinho',
      'Macieira', 'Mafra', 'Mampituba', 'Manoel Viana', 'Maquiné',
      'Maratá', 'Marau', 'Marcelino Ramos', 'Mariana Pimentel', 'Mariano Moro',
      'Marques de Souza', 'Massaranduba', 'Mata', 'Matelândia', 'Matinhos',
      'Mato Castelhano', 'Mato Leitão', 'Mato Queimado', 'Maximiliano de Almeida',
      'Meleiro', 'Miraguaí', 'Mirim Doce', 'Modelo', 'Mondaí',
      'Montauri', 'Monte Alegre dos Campos', 'Monte Belo do Sul', 'Monte Carlo', 'Monte Castelo',
      'Montenegro', 'Mormaço', 'Morro da Fumaça', 'Morro Grande', 'Morro Redondo',
      'Morro Reuter', 'Mostardas', 'Muitos Capões', 'Muliterno', 'Navegantes',
      'Não-Me-Toque', 'Nicolau Vergueiro', 'Nonoai', 'Nova Alvorada', 'Nova Araçá',
      'Nova Bassano', 'Nova Boa Vista', 'Nova Bréscia', 'Nova Candelária', 'Nova Erechim',
      'Nova Esperança do Sul', 'Nova Hartz', 'Nova Itaberaba', 'Nova Palma', 'Nova Pádua',
      'Nova Petrópolis', 'Nova Prata', 'Nova Ramada', 'Nova Roma do Sul', 'Nova Santa Rita',
      'Nova Trento', 'Nova Veneza', 'Novo Barreiro', 'Novo Cabrais', 'Novo Hamburgo',
      'Novo Machado', 'Novo Tiradentes', 'Novo Xingu', 'Osorno', 'Osório',
      'Ouro', 'Ouro Verde', 'Paial', 'Painel', 'Paim Filho',
      'Palhoça', 'Palma Sola', 'Palmares do Sul', 'Palmeira das Missões', 'Palmitinho',
      'Palmitos', 'Panambi', 'Pantano Grande', 'Papanduva', 'Paraí',
      'Paraíso', 'Paraíso do Sul', 'Pareci Novo', 'Parobé', 'Passo do Sobrado',
      'Passo Fundo', 'Passos Maia', 'Paulo Bento', 'Paverama', 'Pedras Altas',
      'Pedras Grandes', 'Pedro Osório', 'Penha', 'Pejuçara', 'Pelotas',
      'Peritiba', 'Pescaria Brava', 'Petrolândia', 'Picada Café', 'Pinhal',
      'Pinhal da Serra', 'Pinhal Grande', 'Pinhalzinho', 'Pinheirinho do Vale',
      'Pinheiro Machado', 'Pinheiro Preto', 'Pinto Bandeira', 'Pirapó', 'Piratuba',
      'Planalto', 'Planalto Alegre', 'Poço das Antas', 'Ponte Preta', 'Ponte Serrada',
      'Pontão', 'Ponte Alta', 'Ponte Alta do Norte', 'Portão', 'Porto Alegre',
      'Porto Belo', 'Porto Lucena', 'Porto Mauá', 'Porto Real do Colégio', 'Porto União',
      'Porto Vera Cruz', 'Porto Xavier', 'Pouso Novo', 'Pouso Redondo', 'Presidente Castello Branco',
      'Presidente Getúlio', 'Presidente Lucena', 'Presidente Nereu', 'Progresso', 'Protásio Alves',
      'Putinga', 'Quaraí', 'Quatro Irmãos', 'Quevedos', 'Quilombo',
      'Quinze de Novembro', 'Redentora', 'Relvado', 'Restinga Seca', 'Rio dos Cedros',
      'Rio dos Índios', 'Rio do Campo', 'Rio do Oeste', 'Rio do Sul', 'Rio Fortuna',
      'Rio Grande', 'Rio Negrinho', 'Rio Pardo', 'Rio Rufino', 'Riqueza',
      'Roca Sales', 'Rodeio', 'Rodeio Bonito', 'Rolador', 'Rolante',
      'Romelândia', 'Ronda Alta', 'Rondinha', 'Roque Gonzales', 'Rosário do Sul',
      'Salete', 'Saldanha Marinho', 'Saltinho', 'Salto do Jacuí', 'Salto Veloso',
      'Salvador das Missões', 'Salvador do Sul', 'Sanga do Norte', 'Sananduva', 'Santa Bárbara do Sul',
      'Santa Cecília', 'Santa Cecília do Sul', 'Santa Clara do Sul', 'Santa Cruz do Sul',
      'Santa Cruz', 'Santa Maria', 'Santa Maria do Herval', 'Santa Margarida do Sul',
      'Santana da Boa Vista', 'Santana do Livramento', 'Santa Rosa', 'Santa Rosa de Lima', 'Santa Rosa do Sul',
      'Santa Tereza', 'Santa Terezinha', 'Santa Terezinha do Progresso', 'Santa Vitória do Palmar',
      'Santiago', 'Santiago do Sul', 'Santo Ângelo', 'Santo Antônio da Patrulha', 'Santo Antônio das Missões',
      'Santo Antônio do Palma', 'Santo Antônio do Planalto', 'Santo Augusto', 'Santo Cristo', 'Santo Expedito do Sul',
      'São Bento', 'São Bento do Sul', 'São Bernardino', 'São Bonifácio', 'São Borja',
      'São Carlos', 'São Cristóvão do Sul', 'São Domingos', 'São Domingos do Sul',
      'São Francisco de Assis', 'São Francisco de Paula', 'São Francisco do Sul', 'São Gabriel',
      'São Jerônimo', 'São João Batista', 'São João do Itaperiú', 'São João do Oeste',
      'São João do Polêsine', 'São João do Sul', 'São Joaquim', 'São Jorge',
      'São José', 'São José do Cedro', 'São José do Cerrito', 'São José do Hortêncio',
      'São José do Inhacorá', 'São José do Norte', 'São José do Ouro', 'São José dos Ausentes',
      'São Leopoldo', 'São Lourenço do Oeste', 'São Lourenço do Sul', 'São Ludgero', 'São Luiz Gonzaga',
      'São Martinho', 'São Martinho da Serra', 'São Miguel da Boa Vista', 'São Miguel das Missões',
      'São Miguel do Oeste', 'São Nicolau', 'São Paulo das Missões', 'São Pedro da Serra',
      'São Pedro das Missões', 'São Pedro do Butiá', 'São Pedro do Sul', 'São Pedro',
      'São Sebastião do Caí', 'São Sepé', 'São Valentim', 'São Valentim do Sul',
      'São Valério do Sul', 'São Vendelino', 'São Vicente do Sul', 'Sapiranga',
      'Sapucaia do Sul', 'Saudades', 'Schroeder', 'Seberi', 'Sede Nova',
      'Segredo', 'Selbach', 'Senador Salgado Filho', 'Sentinela do Sul', 'Serafina Corrêa',
      'Sério', 'Sertão', 'Sertão Santana', 'Sete de Setembro', 'Severiano de Almeida',
      'Siderópolis', 'Silveira Martins', 'Sinimbu', 'Sobradinho', 'Soledade',
      'Sombrio', 'Sul Brasil', 'Tabaí', 'Tapejara', 'Tapera',
      'Tapes', 'Taquara', 'Taquari', 'Taquaruçu do Sul', 'Tavares',
      'Tenente Portela', 'Teotônia', 'Terra de Areia', 'Teutônia', 'Tigrinhos',
      'Timbé do Sul', 'Timbó', 'Tiradentes do Sul', 'Toropi', 'Torres',
      'Tramandaí', 'Travesseiro', 'Treviso', 'Treze de Maio', 'Treze Tílias',
      'Três Arroios', 'Três Cachoeiras', 'Três Coroas', 'Três de Maio', 'Três Forquilhas',
      'Três Palmeiras', 'Três Passos', 'Trindade do Sul', 'Triunfo', 'Tubarão',
      'Tucunduva', 'Tunas', 'Tupanci do Sul', 'Tupanciretã', 'Tupandi',
      'Tuparendi', 'Turvo', 'Ubiretama', 'União da Serra', 'Unistalda',
      'Uruguaiana', 'Urupema', 'Urussanga', 'Vacaria', 'Vale do Sol',
      'Vale Real', 'Vale Verde', 'Vanini', 'Vargeão', 'Vargem',
      'Vargem Bonita', 'Venâncio Aires', 'Vera Cruz', 'Veranópolis', 'Vespasiano Correa',
      'Viadutos', 'Viamão', 'Vicente Dutra', 'Victor Graeff', 'Vidal Ramos',
      'Videira', 'Vila Flores', 'Vila Lângaro', 'Vila Maria', 'Vila Nova do Sul',
      'Vista Alegre', 'Vista Alegre do Prata', 'Vista Gaúcha', 'Vitória das Missões',
      'Westfalia', 'Witmarsum', 'Xangri-lá', 'Xanxerê', 'Xavantina',
      'Xaxim', 'Zortéa'
    ],
    SP: [
        'Adamantina', 'Adolfo', 'Aguaí', 'Águas da Prata', 'Águas de Lindóia',
        'Águas de Santa Bárbara', 'Águas de São Pedro', 'Agudos', 'Alambari', 'Alfredo Marcondes',
        'Altair', 'Altinópolis', 'Alto Alegre', 'Alumínio', 'Álvares Florence', 'Álvares Machado',
        'Álvaro de Carvalho', 'Alvinlândia', 'Americana', 'Américo Brasiliense', 'Américo de Campos',
        'Amparo', 'Analândia', 'Andradina', 'Angatuba', 'Anhembi', 'Anhumas',
        'Aparecida', 'Aparecida d\'Oeste', 'Apiaí', 'Araçariguama', 'Araçatuba', 'Araçoiaba da Serra',
        'Aramina', 'Arandu', 'Arapeí', 'Araraquara', 'Araras', 'Arco-Íris',
        'Arealva', 'Areias', 'Areiópolis', 'Ariranha', 'Artur Nogueira', 'Arujá',
        'Aspásia', 'Assis', 'Atibaia', 'Auriflama', 'Avaí', 'Avanhandava',
        'Avaré', 'Bady Bassitt', 'Balbinos', 'Bálsamo', 'Bananal', 'Barão de Antonina',
        'Barbosa', 'Bariri', 'Barra Bonita', 'Barra do Chapéu', 'Barra do Turvo',
        'Barretos', 'Barrinha', 'Barueri', 'Bastos', 'Batatais', 'Bauru',
        'Bebedouro', 'Bento de Abreu', 'Bernardino de Campos', 'Bertioga', 'Bilac',
        'Birigui', 'Biritiba-Mirim', 'Boa Esperança do Sul', 'Bocaina', 'Bofete',
        'Boituva', 'Bom Jesus dos Perdões', 'Bom Sucesso de Itararé', 'Borá', 'Boracéia',
        'Borborema', 'Borebi', 'Botucatu', 'Bragança Paulista', 'Braúna', 'Brejo Alegre',
        'Brodowski', 'Brotas', 'Buri', 'Buritama', 'Buritizal', 'Cabrália Paulista',
        'Cabreúva', 'Caçapava', 'Cachoeira Paulista', 'Caconde', 'Cafelândia', 'Caiabu',
        'Caieiras', 'Caiuá', 'Cajamar', 'Cajati', 'Cajobi', 'Cajuru',
        'Campina do Monte Alegre', 'Campinas', 'Campo Limpo Paulista', 'Campos do Jordão', 'Campos Novos Paulista',
        'Cananéia', 'Canas', 'Cândido Mota', 'Cândido Rodrigues', 'Canitar', 'Capão Bonito',
        'Capela do Alto', 'Capivari', 'Caraguatatuba', 'Carapicuíba', 'Cardoso', 'Casa Branca',
        'Cássia dos Coqueiros', 'Castilho', 'Catanduva', 'Catiguá', 'Cedral', 'Cerqueira César',
        'Cerquilho', 'Cesário Lange', 'Charqueada', 'Chavantes', 'Clementina', 'Colina',
        'Colômbia', 'Conchal', 'Conchas', 'Cordeirópolis', 'Coroados', 'Coronel Macedo',
        'Corumbataí', 'Cosmópolis', 'Cosmorama', 'Cotia', 'Cravinhos', 'Cristais Paulista',
        'Cruzália', 'Cruzeiro', 'Cubatão', 'Cunha', 'Descalvado', 'Diadema',
        'Dirce Reis', 'Divinolândia', 'Dobrada', 'Dois Córregos', 'Dolcinópolis', 'Dourado',
        'Dracena', 'Duartina', 'Dumont', 'Echaporã', 'Eldorado', 'Elias Fausto',
        'Elisiário', 'Embaúba', 'Embu das Artes', 'Embu-Guaçu', 'Emilianópolis', 'Engenheiro Coelho',
        'Espírito Santo do Pinhal', 'Espírito Santo do Turvo', 'Estiva Gerbi', 'Estrela d\'Oeste', 'Estrela do Norte',
        'Euclides da Cunha Paulista', 'Fartura', 'Fernando Prestes', 'Fernandópolis', 'Fernão', 'Ferraz de Vasconcelos',
        'Flora Rica', 'Floreal', 'Flórida Paulista', 'Florínia', 'Franca', 'Francisco Morato',
        'Franco da Rocha', 'Gabriel Monteiro', 'Gália', 'Garça', 'Gastão Vidigal', 'Gavião Peixoto',
        'General Salgado', 'Getulina', 'Glicério', 'Guaiçara', 'Guaimbê', 'Guaíra',
        'Guapiaçu', 'Guapiara', 'Guará', 'Guaraçaí', 'Guaraci', 'Guarani d\'Oeste',
        'Guarantã', 'Guararapes', 'Guararema', 'Guaratinguetá', 'Guareí', 'Guariba',
        'Guarujá', 'Guarulhos', 'Guatapará', 'Guzolândia', 'Herculândia', 'Holambra',
        'Hortolândia', 'Iacanga', 'Iacri', 'Iaras', 'Ibaté', 'Ibirá',
        'Ibirarema', 'Ibitinga', 'Ibiúna', 'Icém', 'Iepê', 'Igaraçu do Tietê',
        'Igarapava', 'Igaratá', 'Iguape', 'Ilha Comprida', 'Ilha Solteira', 'Ilhabela',
        'Indaiatuba', 'Indiana', 'Indiaporã', 'Inúbia Paulista', 'Ipaussu', 'Iperó',
        'Ipeúna', 'Ipiguá', 'Iporanga', 'Ipuã', 'Iracemápolis', 'Irapuã',
        'Irapuru', 'Itaberá', 'Itaí', 'Itajobi', 'Itaju', 'Itanhaém',
        'Itaoca', 'Itapecerica da Serra', 'Itapetininga', 'Itapeva', 'Itapevi', 'Itapira',
        'Itapirapuã Paulista', 'Itápolis', 'Itaporanga', 'Itapuí', 'Itapura', 'Itaquaquecetuba',
        'Itararé', 'Itariri', 'Itatiba', 'Itatinga', 'Itirapina', 'Itirapuã',
        'Itobi', 'Itu', 'Itupeva', 'Ituverava', 'Jaborandi', 'Jaboticabal',
        'Jacareí', 'Jaci', 'Jacupiranga', 'Jaguariúna', 'Jales', 'Jambeiro',
        'Jandira', 'Jardinópolis', 'Jarinu', 'Jaú', 'Jeriquara', 'Joanópolis',
        'João Ramalho', 'José Bonifácio', 'Júlio Mesquita', 'Jumirim', 'Jundiaí', 'Junqueirópolis',
        'Juquiá', 'Juquitiba', 'Lagoinha', 'Laranjal Paulista', 'Lavínia', 'Lavrinhas',
        'Leme', 'Lençóis Paulista', 'Limeira', 'Lindóia', 'Lins', 'Lorena',
        'Lourdes', 'Louveira', 'Lucélia', 'Lucianópolis', 'Luís Antônio', 'Luiziânia',
        'Lupércio', 'Lutécia', 'Macatuba', 'Macaubal', 'Macedônia', 'Magda',
        'Mairinque', 'Mairiporã', 'Manduri', 'Marabá Paulista', 'Maracaí', 'Marapoama',
        'Mariápolis', 'Marília', 'Marinópolis', 'Martinópolis', 'Matão', 'Mauá',
        'Mendonça', 'Meridiano', 'Mesópolis', 'Miguelópolis', 'Mineiros do Tietê', 'Mira Estrela',
        'Miracatu', 'Mirandópolis', 'Mirante do Paranapanema', 'Mirassol', 'Mirassolândia',
        'Mococa', 'Mogi das Cruzes', 'Mogi Guaçu', 'Mogi Mirim', 'Mombuca', 'Monções',
        'Mongaguá', 'Monte Alegre do Sul', 'Monte Alto', 'Monte Aprazível', 'Monte Azul Paulista',
        'Monte Castelo', 'Monteiro Lobato', 'Monte Mor', 'Morro Agudo', 'Morungaba',
        'Motuca', 'Murutinga do Sul', 'Nantes', 'Narandiba', 'Natividade da Serra', 'Nazaré Paulista',
        'Neves Paulista', 'Nhandeara', 'Nipoã', 'Nova Aliança', 'Nova Campina', 'Nova Canaã Paulista',
        'Nova Castilho', 'Nova Europa', 'Nova Granada', 'Nova Guataporanga', 'Nova Independência', 'Nova Luzitânia',
        'Nova Odessa', 'Novais', 'Novo Horizonte', 'Nuporanga', 'Ocauçu', 'Óleo',
        'Olímpia', 'Onda Verde', 'Oriente', 'Orindiúva', 'Orlândia', 'Osasco',
        'Oscar Bressane', 'Osvaldo Cruz', 'Ourinhos', 'Ouroeste', 'Ouro Verde',
        'Pacaembu', 'Palestina', 'Palmares Paulista', 'Palmeira d\'Oeste', 'Palmital',
        'Panorama', 'Paraguaçu Paulista', 'Paraibuna', 'Paraíso', 'Paranapanema', 'Paranapuã',
        'Parapuã', 'Pardinho', 'Pariquera-Açu', 'Parisi', 'Patrocínio Paulista', 'Paulicéia',
        'Paulínia', 'Paulistânia', 'Paulo de Faria', 'Pederneiras', 'Pedra Bela', 'Pedranópolis',
        'Pedregulho', 'Pedreira', 'Pedrinhas Paulista', 'Pedro de Toledo', 'Penápolis', 'Pereira Barreto',
        'Pereiras', 'Peruíbe', 'Piacatu', 'Piedade', 'Pilar do Sul', 'Pindamonhangaba',
        'Pindorama', 'Pinhalzinho', 'Piquerobi', 'Piquete', 'Piracaia', 'Piracicaba',
        'Piraju', 'Pirajuí', 'Pirangi', 'Pirapora do Bom Jesus', 'Pirapozinho',
        'Pirassununga', 'Piratininga', 'Pitangueiras', 'Planalto', 'Platina', 'Poá',
        'Poloni', 'Pompéia', 'Pongaí', 'Pontal', 'Pontalinda', 'Pontes Gestal',
        'Populina', 'Porangaba', 'Porto Feliz', 'Porto Ferreira', 'Potim', 'Potirendaba',
        'Pracinha', 'Pradópolis', 'Praia Grande', 'Pratânia', 'Presidente Alves', 'Presidente Bernardes',
        'Presidente Epitácio', 'Presidente Prudente', 'Presidente Venceslau', 'Promissão', 'Quadra',
        'Quatá', 'Queiroz', 'Queluz', 'Quintana', 'Rafard', 'Rancharia',
        'Redenção da Serra', 'Regente Feijó', 'Reginópolis', 'Registro', 'Restinga', 'Ribeira',
        'Ribeirão Bonito', 'Ribeirão Branco', 'Ribeirão Corrente', 'Ribeirão do Sul', 'Ribeirão dos Índios',
        'Ribeirão Grande', 'Ribeirão Pires', 'Ribeirão Preto', 'Rifaina', 'Rincão', 'Rinópolis',
        'Rio Claro', 'Rio das Pedras', 'Rio Grande da Serra', 'Riolândia', 'Riversul', 'Rosana',
        'Roseira', 'Rubiácea', 'Rubinéia', 'Sabino', 'Sagres', 'Sales',
        'Sales Oliveira', 'Salesópolis', 'Salmourão', 'Saltinho', 'Salto', 'Salto de Pirapora',
        'Salto Grande', 'Sandovalina', 'Santa Adélia', 'Santa Albertina', 'Santa Bárbara d\'Oeste', 'Santa Branca',
        'Santa Clara d\'Oeste', 'Santa Cruz da Conceição', 'Santa Cruz da Esperança', 'Santa Cruz das Palmeiras',
        'Santa Cruz do Rio Pardo', 'Santa Ernestina', 'Santa Fé do Sul', 'Santa Gertrudes', 'Santa Isabel',
        'Santa Lúcia', 'Santa Maria da Serra', 'Santa Mercedes', 'Santana da Ponte Pensa', 'Santana de Parnaíba',
        'Santa Rita d\'Oeste', 'Santa Rita do Passa Quatro', 'Santa Rosa de Viterbo', 'Santa Salete', 'Santo Anastácio',
        'Santo André', 'Santo Antônio da Alegria', 'Santo Antônio de Posse', 'Santo Antônio do Aracanguá',
        'Santo Antônio do Jardim', 'Santo Antônio do Pinhal', 'Santo Expedito', 'Santópolis do Aguapeí',
        'Santos', 'São Bento do Sapucaí', 'São Bernardo do Campo', 'São Caetano do Sul', 'São Carlos', 'São Francisco',
        'São João da Boa Vista', 'São João das Duas Pontes', 'São João de Iracema', 'São João do Pau d\'Alho',
        'São Joaquim da Barra', 'São José da Bela Vista', 'São José do Barreiro', 'São José do Rio Pardo',
        'São José do Rio Preto', 'São José dos Campos', 'São Lourenço da Serra', 'São Luís do Paraitinga',
        'São Manuel', 'São Miguel Arcanjo', 'São Paulo', 'São Pedro', 'São Pedro do Turvo', 'São Roque',
        'São Sebastião', 'São Sebastião da Grama', 'São Simão', 'São Vicente', 'Sarapuí', 'Sarutaiá',
        'Sebastianópolis do Sul', 'Serra Azul', 'Serra Negra', 'Serrana', 'Sertãozinho', 'Sete Barras',
        'Severínia', 'Silveiras', 'Socorro', 'Sorocaba', 'Sud Mennucci', 'Sumaré', 'Suzanápolis',
        'Suzano', 'Tabapuã', 'Tabatinga', 'Taboão da Serra', 'Taciba', 'Taguaí', 'Taiaçu',
        'Taiúva', 'Tambaú', 'Tanabi', 'Tapiraí', 'Tapiratiba', 'Taquaral', 'Taquaritinga',
        'Taquarituba', 'Taquarivaí', 'Tarabai', 'Tarumã', 'Tatuí', 'Taubaté',
        'Tejupá', 'Teodoro Sampaio', 'Terra Roxa', 'Tietê', 'Timburi', 'Torre de Pedra',
        'Torrinha', 'Trabiju', 'Tremembé', 'Três Fronteiras', 'Tuiuti', 'Tupã',
        'Tupi Paulista', 'Turiúba', 'Turmalina', 'Ubarana', 'Ubatuba', 'Ubirajara',
        'Uchoa', 'União Paulista', 'Urânia', 'Uru', 'Urupês', 'Valentim Gentil',
        'Valinhos', 'Valparaíso', 'Vargem', 'Vargem Grande do Sul', 'Vargem Grande Paulista',
        'Várzea Paulista', 'Vera Cruz', 'Vinhedo', 'Viradouro', 'Vista Alegre do Alto',
        'Vitória Brasil', 'Votorantim', 'Votuporanga', 'Zacarias'
    ],
    SE: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto', 'Itabaiana', 'São Cristóvão', 'Estância'],
    TO: ['Palmas', 'Araguaína', 'Gurupi', 'Porto Nacional', 'Paraíso do Tocantins']
};
